## Build Docker Image
# parameters:
#   - name: imageName
#     type: string
#     default: 'awesome-fastapi'



jobs:
  - job:
    steps:
      - checkout: self
        displayName: 'Checkout repo'
     
      - script: |
          echo "Building Docker image..."
          docker build -t awesome-fastapi:$(Build.SourceVersion) .
        displayName: 'Build Docker Image'

