jobs:
  - job:
    steps:
      - checkout: self
        displayName: "Checkout repo"

      - script: |
          echo "Building Docker image..."
          docker build -t python-fastapi:$(Build.SourceVersion) .
        displayName: "Build Docker Image"
