jobs:
  - job: push_image
    displayName: "Build and Push Docker Image"
    pool:
      vmImage: "ubuntu-latest"
    steps:
      - checkout: self
        displayName: "Checkout repo"

      - script: |
          echo "ACR_SERVICE_CONNECTION: $(ACR_SERVICE_CONNECTION)"
          echo "ACR_URL: $(ACR_URL)"
        displayName: "Show variable values"

      ### Push the Docker image to Azure Container Registry ###
      - task: Docker@2
        displayName: "Build and Push Docker Image to ACR"
        inputs:
          command: buildAndPush
          containerRegistry: $(ACR_SERVICE_CONNECTION) # name of your ADO service connection to ACR
          repository: $(ACR_URL)/apps/python-fastapi # e.g. myacr.azurecr.io/myapp
          dockerfile: ./Dockerfile # e.g. Dockerfile
          tags: latest