jobs:
  - job: testing_phase
    displayName: "Run unit test"
    pool:
      vmImage: ubuntu-latest

      steps:
        - checkout: self
          displayName: "Checkout repo"

        - script: |
            echo "installing dependencies..."
            pip install -r requirements.txt
          displayName: "Install dependencies"

        - script: |
            echo "running py tests..."
            pytest test/
          displayName: "Run python tests"

  - job: trivy_dependency_scan
    displayName: "Trivy - Scan dependencies for vulnerabilities"
    pool:
      vmImage: ubuntu-latest

    steps:
      - checkout: self
        displayName: "Checkout repo"

      - script: |
          echo "Building Docker image..."
          docker build -t python-fastapi:$(Build.SourceVersion) .
        displayName: "Build Docker Image"

      - script: |
          docker run --rm \
            -v $(Build.SourcesDirectory):/app \
            aquasec/trivy:latest fs /app \
              --exit-code 1 \
              --severity HIGH,CRITICAL
        displayName: "Trivy scan source files"

  - job: trivy_image_scan
    displayName: "Run Trivy security scanner against the image"
    pool:
      vmImage: ubuntu-latest

    steps:
      - checkout: self
        displayName: "Checkout repo"

      - script: |
          echo "Building Docker image..."
          docker build -t python-fastapi:$(Build.SourceVersion) .
        displayName: "Build Docker Image"

      # Make sure you set the exit code to 1 to fail the build on vulnerabilities
      - script: |
          docker run --rm \
            -v /var/run/docker.sock:/var/run/docker.sock \
            aquasec/trivy:latest image python-fastapi:$(Build.SourceVersion) \
              --exit-code 0 \
              --severity HIGH,CRITICAL
        displayName: "Trivy scan image"

  - job: owasp_zap_scan
    pool:
      vmImage: ubuntu-latest
    displayName: "Run OWASP ZAP security scanner"
    steps:
      - checkout: self
        displayName: "Checkout repo"

        # Build and Tag Image
        # Run Docker Image in detached mode
      - script: |
          echo "Building Docker image..."
          docker build -t python-fastapi:$(Build.SourceVersion) .
          docker run -d -p 8080:8080 python-fastapi:$(Build.SourceVersion)
        displayName: "Build Docker Image"

      - script: sleep 30
        displayName: "Wait for Docker container to be ready"

      - script: docker ps
        displayName: "Confirm Docker container is running"

      - script: |
          mkdir -p "$(Build.SourcesDirectory)/zap-out"
          docker run --rm -t \
            -u 0:0 \
            -v "$(Build.SourcesDirectory)/zap-out:/zap/wrk:rw" \
            ghcr.io/zaproxy/zaproxy:stable \
            zap-full-scan.py -t "http://host.docker.internal:8080" 2>&1 | tee "$(Build.SourcesDirectory)/zap-out/zap-scan.log" || true

          echo "===== ZAP Scan Results ====="
          cat "$(Build.SourcesDirectory)/zap-out/zap-scan.log"
        displayName: "Run ZAP full scan"

