apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-fastapi
  labels:
    app: python-fastapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-fastapi
  template:
    metadata:
      labels:
        app: python-fastapi
    spec:
      containers:
        - name: python-fastapi
          image: myacr.azurecr.io/apps/python-fastapi:latest # This will be replaced by your pipeline
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: python-fastapi-service
spec:
  type: LoadBalancer
  selector:
    app: python-fastapi
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
